name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: sidyusufdev/sidyusufdev
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          COMMIT_MESSAGE: "Updated WakaTime stats"
